import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './providers'
import classnames from 'classnames';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    // TODO: Figure out dynamic theme switching between dark and light modes
  return (

      <html lang="en" suppressHydrationWarning>
          <head title="Seanario" />
          <body className={classnames('min-h-screen mx-auto max-w-6xl flex flex-col bg-white dark:bg-gray-900', inter.className)}>
              <Providers>{children}</Providers>
          </body>
      </html>
  );
}
